services:
  - type: web
    plan: free
    name: ARTFWD
    env: docker
    #buildCommand: pip install -U -r requirements.txt
    #startCommand: gunicorn app:app & python3 -m Zaid
    repo: hhttps://github.com/assc0d3r/ART-Forward-Client     
    branch: master
    envVars:
      - key: API_ID 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: API_HASH 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_URL
        sync: false
      - key: FORWARD_FILTERS
        sync: false    
      - key: FORWARD_TO_CHAT_ID
        sync: false  
      - key: FORWARD_FROM_CHAT_ID
        sync: false  
      - key: FORWARD_AS_COPY
        sync: false  
      - key: BLOCKED_EXTENSIONS
        sync: false  
      - key: MINIMUM_FILE_SIZE
        sync: false  
      - key: BLOCK_FILES_WITHOUT_EXTENSIONS
        sync: false  
    autoDeploy: false
